### ISSUE TITLE
Start a modpack server with sponge

### ISSUE THREAD

**Issue by FabiusHaselnuss** [CursedFlames/BountifulBaubles#67]
Transformed Time of day!
main/INFO12:24:51
[java.lang.ThreadGroup:uncaughtException:1059]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[java.lang.ThreadGroup:uncaughtException:1059]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[java.lang.ThreadGroup:uncaughtException:1059]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[java.lang.ThreadGroup:uncaughtException:1059]: at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37)
[java.lang.ThreadGroup:uncaughtException:1059]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[java.lang.ThreadGroup:uncaughtException:1059]: ... 7 more
[java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[java.lang.Throwable:printStackTrace:648]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[java.lang.Throwable:printStackTrace:648]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[java.lang.Throwable:printStackTrace:648]: at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[java.lang.Throwable:printStackTrace:648]: at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[java.lang.Throwable:printStackTrace:648]: at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[java.lang.Throwable:printStackTrace:648]: at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[java.lang.Throwable:printStackTrace:648]: at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[java.lang.Throwable:printStackTrace:648]: at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[java.lang.Throwable:printStackTrace:648]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[java.lang.Throwable:printStackTrace:648]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[java.lang.Throwable:printStackTrace:648]: at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[java.lang.Throwable:printStackTrace:648]: at net.minecraft.server.Main.main(Main.java:92)
[java.lang.Throwable:printStackTrace:648]: ... 13 more
[java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method onApplyDamageAmount(FLnet/minecraft/util/DamageSource;)F in bountifulbaubles.mixins.json:MixinPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bountifulbaubles-common-refmap.json
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[java.lang.Throwable:printStackTrace:671]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[java.lang.Throwable:printStackTrace:671]: ... 33 more
Console12:24:51
Exception in thread "main"

**Comment by TheHalfPotato** [comment]
I have the same issue, did you find a solution?

**Comment by SikiciBebek** [comment]
u have to remove it
it works without the mod
